services:
  fyp:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    volumes:
      - ..:/app

    container_name: fyp_devsecops
    tty: true
    stdin_open: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]